Add files via upload
ValueError: Input contains NaN, infinity or a value too large for dtype('float64'), when doing the logistic regression
ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters, when doing the train-test